//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportService.DataAccess.Repositories.Sql.StopResumeAct {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportService.DataAccess.Repositories.Sql.StopResumeAct.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id AS &quot;Id&quot;,
        ///       request_id AS &quot;RequestId&quot;,
        ///       type AS &quot;Type&quot;,
        ///       work_time AS &quot;WorkTime&quot;,
        ///       address AS &quot;Address&quot;,
        ///       has_commuting_device AS &quot;HasCommutingDevice&quot;,
        ///       result AS &quot;Result&quot;,
        ///       work_method AS &quot;WorkMethod&quot;,
        ///       metering_device_location_type AS &quot;MeteringDeviceLocationType&quot;,
        ///       metering_device_location AS &quot;MeteringsDevieLocation&quot;,
        ///       device_readings AS &quot;DeviceReadings&quot;,
        ///       work_method_type AS &quot;WorkMethodType&quot;,
        ///       workers AS &quot;Workers&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetByRequestId {
            get {
                return ResourceManager.GetString("GetByRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO stop_resume_acts(request_id, type, work_time, address, has_commuting_device, result, work_method, metering_device_location_type, metering_device_location, device_readings, work_method_type, workers, client_full_name)
        ///VALUES(@RequestId, @Type, @WorkTime, @Address, @HasCommutingDevice, @Result, @WorkMethod, @MeteringDeviceLocationType, @MeteringDeviceLocation, @DeviceReadings, @WorkMethodType, @Workers, @ClientFUllName).
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
    }
}
