//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportService.DataAccess.Repositories.Sql.ControlAct {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportService.DataAccess.Repositories.Sql.ControlAct.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id AS &quot;Id&quot;,
        ///       request_id AS &quot;RequestId&quot;,
        ///       is_authorized_connection AS &quot;IsAuthorizedConnection&quot;,
        ///       work_time AS &quot;WorkTime&quot;,
        ///       address AS &quot;Address&quot;,
        ///       has_commuting_device AS &quot;HasCommutingDevice&quot;,
        ///       has_violation AS &quot;HasViolation&quot;,
        ///       metering_device_location_type AS &quot;MeteringDeviceLocationType&quot;,
        ///       metering_device_location AS &quot;MeteringDeviceLocation&quot;,
        ///       device_readings AS &quot;DeviceReadings&quot;,
        ///       workers AS &quot;Workers&quot;
        ///FROM control_acts
        ///WHERE reque [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetByRequestId {
            get {
                return ResourceManager.GetString("GetByRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO control_acts(request_id, is_unauthorized_connection, work_time, address, has_commuting_device, has_violation, metering_device_location_type, metering_device_location, device_readings, workers)
        ///VALUES(@RequestId, @IsUnauthorizedConnection, @WorkTime, @Address, @HasCommutingDevice, @HasViolation, @MeteringDeviceLocationType, @MeteringDeviceLocation, @DeviceReadings, @Workers).
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
    }
}
